package com.leco.meterreader.util

import android.content.Context
import android.content.Intent
import android.os.Environment
import androidx.core.content.FileProvider
import java.io.File
import java.io.FileWriter
import java.io.IOException
import java.time.LocalDate
import java.time.format.DateTimeFormatter

/**
 * Utility class for exporting chart data to CSV format
 */
object CSVExportUtils {
    
    private val formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd")
    private val displayFormatter = DateTimeFormatter.ofPattern("MMM dd, yyyy")
    
    /**
     * Exports analytics data to CSV file and shares it
     */
    fun exportAndShareAnalyticsData(
        context: Context,
        dailyData: List<DailyUsageData>,
        weeklyData: List<WeeklyTrendData>,
        touData: List<TOUComparisonData>,
        dateRange: com.leco.meterreader.viewmodel.DateRange?,
        fileName: String = "leco_analytics_export_${LocalDate.now().format(formatter)}.csv"
    ): Boolean {
        try {
            // Create CSV content
            val csvContent = generateCSVContent(
                dailyData,
                weeklyData,
                touData,
                dateRange
            )
            
            // Save to file
            val file = saveCSVToFile(context, csvContent, fileName)
            
            // Share the file
            shareCSVFile(context, file)
            
            return true
        } catch (e: Exception) {
            e.printStackTrace()
            return false
        }
    }
    
    /**
     * Generates CSV content from chart data
     */
    fun generateCSVContent(
        dailyData: List<DailyUsageData>,
        weeklyData: List<WeeklyTrendData>,
        touData: List<TOUComparisonData>,
        dateRange: com.leco.meterreader.viewmodel.DateRange?
    ): String {
        val csvBuilder = StringBuilder()
        
        // CSV Header
        csvBuilder.append("LECO Solar Meter Analyzer - Analytics Data Export\n")
        csvBuilder.append("Export Date: ${LocalDate.now().format(displayFormatter)}\n")
        csvBuilder.append("Date Range: ${dateRange?.start?.format(displayFormatter) ?: "Not specified"} - ${dateRange?.end?.format(displayFormatter) ?: "Not specified"}\n")
        csvBuilder.append("Generated by: LECO Solar Meter Analyzer App\n\n")
        
        // Summary Statistics
        csvBuilder.append("=== SUMMARY STATISTICS ===\n")
        csvBuilder.append("Total Period Consumption: ${String.format("%.3f", dailyData.sumOf { it.totalUsage })} kWh\n")
        csvBuilder.append("Average Daily Usage: ${String.format("%.3f", dailyData.map { it.totalUsage }.average())} kWh\n")
        csvBuilder.append("Number of Days: ${dailyData.size}\n")
        csvBuilder.append("Number of Weeks: ${weeklyData.size}\n")
        csvBuilder.append("Total Off-Peak Usage: ${String.format("%.3f", touData.sumOf { it.offPeakUsage })} kWh\n")
        csvBuilder.append("Total Day Usage: ${String.format("%.3f", touData.sumOf { it.dayUsage })} kWh\n")
        csvBuilder.append("Total Peak Usage: ${String.format("%.3f", touData.sumOf { it.peakUsage })} kWh\n\n")
        
        // Daily Usage Data
        csvBuilder.append("=== DAILY USAGE DATA ===\n")
        csvBuilder.append("Date,Total Usage (kWh),Rate 1 (kWh),Rate 2 (kWh),Rate 3 (kWh)\n")
        
        dailyData.forEach { data ->
            csvBuilder.append("${data.date.format(formatter)},")
            csvBuilder.append("${String.format("%.3f", data.totalUsage)},")
            csvBuilder.append("${String.format("%.3f", data.rate1Usage)},")
            csvBuilder.append("${String.format("%.3f", data.rate2Usage)},")
            csvBuilder.append("${String.format("%.3f", data.rate3Usage)}\n")
        }
        
        csvBuilder.append("\n")
        
        // Weekly Trends Data
        csvBuilder.append("=== WEEKLY TRENDS DATA ===\n")
        csvBuilder.append("Week Start,Week End,Total Usage (kWh),Average Daily (kWh),Previous Week (kWh)\n")
        
        weeklyData.forEach { data ->
            csvBuilder.append("${data.weekStart.format(formatter)},")
            csvBuilder.append("${data.weekEnd.format(formatter)},")
            csvBuilder.append("${String.format("%.3f", data.totalUsage)},")
            csvBuilder.append("${String.format("%.3f", data.averageUsage)},")
            csvBuilder.append("${String.format("%.3f", data.previousWeekUsage ?: 0)}\n")
        }
        
        csvBuilder.append("\n")
        
        // TOU Comparison Data
        csvBuilder.append("=== TIME OF USE COMPARISON DATA ===\n")
        csvBuilder.append("Date,Off-Peak (kWh),Day (kWh),Peak (kWh),Total (kWh)\n")
        
        touData.forEach { data ->
            csvBuilder.append("${data.date.format(formatter)},")
            csvBuilder.append("${String.format("%.3f", data.offPeakUsage)},")
            csvBuilder.append("${String.format("%.3f", data.dayUsage)},")
            csvBuilder.append("${String.format("%.3f", data.peakUsage)},")
            csvBuilder.append("${String.format("%.3f", data.totalUsage)}\n")
        }
        
        csvBuilder.append("\n")
        
        // TOU Summary
        csvBuilder.append("=== TOU SUMMARY ===\n")
        val totalOffPeak = touData.sumOf { it.offPeakUsage }
        val totalDay = touData.sumOf { it.dayUsage }
        val totalPeak = touData.sumOf { it.peakUsage }
        val totalOverall = totalOffPeak + totalDay + totalPeak
        
        csvBuilder.append("Total Off-Peak Usage: ${String.format("%.3f", totalOffPeak)} kWh (${String.format("%.1f", (totalOffPeak / totalOverall) * 100)}%)\n")
        csvBuilder.append("Total Day Usage: ${String.format("%.3f", totalDay)} kWh (${String.format("%.1f", (totalDay / totalOverall) * 100)}%)\n")
        csvBuilder.append("Total Peak Usage: ${String.format("%.3f", totalPeak)} kWh (${String.format("%.1f", (totalPeak / totalOverall) * 100)}%)\n")
        
        return csvBuilder.toString()
    }
    
    /**
     * Saves CSV content to a file
     */
    private fun saveCSVToFile(
        context: Context,
        content: String,
        fileName: String
    ): File {
        val downloadsDir = Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_DOWNLOADS)
        val file = File(downloadsDir, fileName)
        
        FileWriter(file).use { writer ->
            writer.write(content)
            writer.flush()
        }
        
        return file
    }
    
    /**
     * Shares the CSV file using Android share intent
     */
    private fun shareCSVFile(
        context: Context,
        file: File
    ) {
        val uri = FileProvider.getUriForFile(
            context,
            "${context.packageName}.fileprovider",
            file
        )
        
        val intent = Intent(Intent.ACTION_SEND).apply {
            type = "text/csv"
            putExtra(Intent.EXTRA_STREAM, uri)
            putExtra(Intent.EXTRA_SUBJECT, "LECO Analytics Data Export")
            putExtra(Intent.EXTRA_TEXT, "Analytics data exported from LECO Solar Meter Analyzer App")
            addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION)
        }
        
        val chooser = Intent.createChooser(intent, "Share Analytics Data")
        context.startActivity(chooser)
    }
    
    /**
     * Validates if data is suitable for export
     */
    fun validateExportData(
        dailyData: List<DailyUsageData>,
        weeklyData: List<WeeklyTrendData>,
        touData: List<TOUComparisonData>
    ): ExportValidationResult {
        val errors = mutableListOf<String>()
        
        if (dailyData.isEmpty()) {
            errors.add("No daily usage data available for export")
        }
        
        if (weeklyData.isEmpty()) {
            errors.add("No weekly trends data available for export")
        }
        
        if (touData.isEmpty()) {
            errors.add("No TOU comparison data available for export")
        }
        
        return ExportValidationResult(
            isValid = errors.isEmpty(),
            errors = errors
        )
    }
    
    /**
     * Gets suggested file name based on date range
     */
    fun getSuggestedFileName(
        dateRange: com.leco.meterreader.viewmodel.DateRange?
    ): String {
        return if (dateRange != null) {
            val start = dateRange.start.format(formatter)
            val end = dateRange.end.format(formatter)
            "leco_analytics_${start}_to_${end}.csv"
        } else {
            "leco_analytics_${LocalDate.now().format(formatter)}.csv"
        }
    }
    
    /**
     * Export validation result
     */
    data class ExportValidationResult(
        val isValid: Boolean,
        val errors: List<String>
    )
    
    /**
     * Export options
     */
    enum class ExportOption {
        DAILY_DATA_ONLY,
        WEEKLY_DATA_ONLY,
        TOU_DATA_ONLY,
        ALL_DATA,
        SUMMARY_ONLY
    }
    
    /**
     * Generates CSV for specific export option
     */
    fun generateCSVForOption(
        option: ExportOption,
        dailyData: List<DailyUsageData>,
        weeklyData: List<WeeklyTrendData>,
        touData: List<TOUComparisonData>,
        dateRange: com.leco.meterreader.viewmodel.DateRange?
    ): String {
        return when (option) {
            ExportOption.DAILY_DATA_ONLY -> generateDailyDataCSV(dailyData, dateRange)
            ExportOption.WEEKLY_DATA_ONLY -> generateWeeklyDataCSV(weeklyData, dateRange)
            ExportOption.TOU_DATA_ONLY -> generateTOUDataCSV(touData, dateRange)
            ExportOption.ALL_DATA -> generateCSVContent(dailyData, weeklyData, touData, dateRange)
            ExportOption.SUMMARY_ONLY -> generateSummaryCSV(dailyData, weeklyData, touData, dateRange)
        }
    }
    
    /**
     * Generates daily data only CSV
     */
    private fun generateDailyDataCSV(
        dailyData: List<DailyUsageData>,
        dateRange: com.leco.meterreader.viewmodel.DateRange?
    ): String {
        val csvBuilder = StringBuilder()
        
        csvBuilder.append("LECO Solar Meter Analyzer - Daily Usage Data Export\n")
        csvBuilder.append("Export Date: ${LocalDate.now().format(displayFormatter)}\n")
        csvBuilder.append("Date Range: ${dateRange?.start?.format(displayFormatter) ?: "Not specified"} - ${dateRange?.end?.format(displayFormatter) ?: "Not specified"}\n\n")
        
        csvBuilder.append("Date,Total Usage (kWh),Rate 1 (kWh),Rate 2 (kWh),Rate 3 (kWh)\n")
        
        dailyData.forEach { data ->
            csvBuilder.append("${data.date.format(formatter)},")
            csvBuilder.append("${String.format("%.3f", data.totalUsage)},")
            csvBuilder.append("${String.format("%.3f", data.rate1Usage)},")
            csvBuilder.append("${String.format("%.3f", data.rate2Usage)},")
            csvBuilder.append("${String.format("%.3f", data.rate3Usage)}\n")
        }
        
        return csvBuilder.toString()
    }
    
    /**
     * Generates weekly data only CSV
     */
    private fun generateWeeklyDataCSV(
        weeklyData: List<WeeklyTrendData>,
        dateRange: com.leco.meterreader.viewmodel.DateRange?
    ): String {
        val csvBuilder = StringBuilder()
        
        csvBuilder.append("LECO Solar Meter Analyzer - Weekly Trends Data Export\n")
        csvBuilder.append("Export Date: ${LocalDate.now().format(displayFormatter)}\n")
        csvBuilder.append("Date Range: ${dateRange?.start?.format(displayFormatter) ?: "Not specified"} - ${dateRange?.end?.format(displayFormatter) ?: "Not specified"}\n\n")
        
        csvBuilder.append("Week Start,Week End,Total Usage (kWh),Average Daily (kWh),Previous Week (kWh)\n")
        
        weeklyData.forEach { data ->
            csvBuilder.append("${data.weekStart.format(formatter)},")
            csvBuilder.append("${data.weekEnd.format(formatter)},")
            csvBuilder.append("${String.format("%.3f", data.totalUsage)},")
            csvBuilder.append("${String.format("%.3f", data.averageUsage)},")
            csvBuilder.append("${String.format("%.3f", data.previousWeekUsage ?: 0)}\n")
        }
        
        return csvBuilder.toString()
    }
    
    /**
     * Generates TOU data only CSV
     */
    private fun generateTOUDataCSV(
        touData: List<TOUComparisonData>,
        dateRange: com.leco.meterreader.viewmodel.DateRange?
    ): String {
        val csvBuilder = StringBuilder()
        
        csvBuilder.append("LECO Solar Meter Analyzer - TOU Comparison Data Export\n")
        csvBuilder.append("Export Date: ${LocalDate.now().format(displayFormatter)}\n")
        csvBuilder.append("Date Range: ${dateRange?.start?.format(displayFormatter) ?: "Not specified"} - ${dateRange?.end?.format(displayFormatter) ?: "Not specified"}\n\n")
        
        csvBuilder.append("Date,Off-Peak (kWh),Day (kWh),Peak (kWh),Total (kWh)\n")
        
        touData.forEach { data ->
            csvBuilder.append("${data.date.format(formatter)},")
            csvBuilder.append("${String.format("%.3f", data.offPeakUsage)},")
            csvBuilder.append("${String.format("%.3f", data.dayUsage)},")
            csvBuilder.append("${String.format("%.3f", data.peakUsage)},")
            csvBuilder.append("${String.format("%.3f", data.totalUsage)}\n")
        }
        
        return csvBuilder.toString()
    }
    
    /**
     * Generates summary only CSV
     */
    private fun generateSummaryCSV(
        dailyData: List<DailyUsageData>,
        weeklyData: List<WeeklyTrendData>,
        touData: List<TOUComparisonData>,
        dateRange: com.leco.meterreader.viewmodel.DateRange?
    ): String {
        val csvBuilder = StringBuilder()
        
        csvBuilder.append("LECO Solar Meter Analyzer - Analytics Summary Export\n")
        csvBuilder.append("Export Date: ${LocalDate.now().format(displayFormatter)}\n")
        csvBuilder.append("Date Range: ${dateRange?.start?.format(displayFormatter) ?: "Not specified"} - ${dateRange?.end?.format(displayFormatter) ?: "Not specified"}\n\n")
        
        csvBuilder.append("=== SUMMARY STATISTICS ===\n")
        csvBuilder.append("Total Period Consumption: ${String.format("%.3f", dailyData.sumOf { it.totalUsage })} kWh\n")
        csvBuilder.append("Average Daily Usage: ${String.format("%.3f", dailyData.map { it.totalUsage }.average())} kWh\n")
        csvBuilder.append("Number of Days: ${dailyData.size}\n")
        csvBuilder.append("Number of Weeks: ${weeklyData.size}\n")
        csvBuilder.append("Total Off-Peak Usage: ${String.format("%.3f", touData.sumOf { it.offPeakUsage })} kWh\n")
        csvBuilder.append("Total Day Usage: ${String.format("%.3f", touData.sumOf { it.dayUsage })} kWh\n")
        csvBuilder.append("Total Peak Usage: ${String.format("%.3f", touData.sumOf { it.peakUsage })} kWh\n")
        
        return csvBuilder.toString()
    }
}